### ISSUE TITLE
Can you show an Infinite Carousel Example?

### ISSUE THREAD

**Issue by Jaypatelbond** [KoderLabs/finite-cover-flow#1]
They are all example of the finite carousel. Would you give an example of Infinite Carousel?

**Comment by saeed-younus** [comment]
Yes, it will also work for for infinite items, I will add example fir infinite items in two or three days. @Jaypatelbond

**Comment by Jaypatelbond** [comment]
That helps bruh, Actually, the app name says **Infinite Example**, So I directly asked you for that! Hope to see the example soon. @saeed-younus 😀

**Comment by saeed-younus** [comment]
I will comment and close the issue when done

**Comment by Jaypatelbond** [comment]
I think you should label this as **Enhancement**

**Comment by saeed-younus** [comment]
I added infinite scrolling example you can checked @Jaypatelbond I am closing this issue.

**Comment by Jaypatelbond** [comment]
You haven't given the reference. @saeed-younus

**Comment by saeed-younus** [comment]
I added an activity in example refer the link, how you can implement your own infinite scrolling logic, 
https://github.com/KoderLabs/finite-cover-flow/blob/dev/app/src/main/java/com/saeed/finiteflow/example/infinitepagerexample/InfiniteHorizontalCrouselExampleActivity.kt

**Comment by Jaypatelbond** [comment]
Will send the reference to that. Actually you did a great job.
